import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const TrustGraph = await ethers.getContractFactory("TrustGraph");
  const trustGraph = await TrustGraph.deploy();

  await trustGraph.waitForDeployment();

  const address = await trustGraph.getAddress();
  console.log("TrustGraph deployed to:", address);

  const clientLibPath = path.join(__dirname, "../../client/src/lib");
  const contractAddressPath = path.join(clientLibPath, "contractAddress.ts");
  const abiDestPath = path.join(clientLibPath, "TrustGraph.json");

  fs.mkdirSync(clientLibPath, { recursive: true });

  fs.writeFileSync(
    contractAddressPath,
    `// Auto-generated by deployment script. Do not edit manually.\nexport const TRUST_GRAPH_ADDRESS = "${address}" as const;\n`,
    "utf-8"
  );
  console.log("Written contract address to:", contractAddressPath);

  const artifactPath = path.join(
    __dirname,
    "../artifacts/contracts/TrustGraph.sol/TrustGraph.json"
  );
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
  fs.writeFileSync(abiDestPath, JSON.stringify(artifact.abi, null, 2), "utf-8");
  console.log("Written ABI to:", abiDestPath);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
